// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Wed May 26 10:34:47 2021

top_layer top_layer_inst
(
	.start(start_sig) ,	// input  start_sig
	.dram_in(dram_in_sig) ,	// input [15:0] dram_in_sig
	.iram_in(iram_in_sig) ,	// input [15:0] iram_in_sig
	.data_out(data_out_sig) ,	// output [15:0] data_out_sig
	.addr_out(addr_out_sig) ,	// output [15:0] addr_out_sig
	.mem_write(mem_write_sig) 	// output [1:0] mem_write_sig
);

